(()=>{"use strict";
const DATA=window.KOWA_GUIDE,CFG=window.KOWA_CONFIG||{},KEY="kowa.static.v1",CLOCK_KEY="kowa.static.clocks.v1",ACTOR_KEY="kowa.actor.v1";
const defaults={activeMap:null,mode:null,tab:"guide",progress:{},notes:{},favorites:{},players:4,sideQuest:null,focusKey:null,openSection:null,query:"",squadCode:null,playerName:"",activeZone:null,details:{}};
let state=load(KEY,defaults),clocks=load(CLOCK_KEY,{}),lamport=Math.max(0,...Object.values(clocks).map(c=>c?.n||0)),actorId=localStorage.getItem(ACTOR_KEY),undoSnapshot=null,undoTimer=null,squad=null;
if(!actorId){actorId=crypto.randomUUID?.()||Math.random().toString(36).slice(2);localStorage.setItem(ACTOR_KEY,actorId)}
const $=s=>document.querySelector(s);
function load(k,f){try{const x=JSON.parse(localStorage.getItem(k));return x?{...structuredClone(f),...x}:structuredClone(f)}catch{return structuredClone(f)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(CLOCK_KEY,JSON.stringify(clocks))}
function setPath(obj,path,value){const p=path.split(".");let c=obj;for(let i=0;i<p.length-1;i++){c[p[i]]??={};c=c[p[i]]}c[p.at(-1)]=value}
function getPath(obj,path){return path.split(".").reduce((a,k)=>a?.[k],obj)}
function newer(a,b){return !b||a.n>b.n||(a.n===b.n&&String(a.actor)>String(b.actor))}
function localSet(path,value,broadcast=true){lamport++;const clock={n:lamport,actor:actorId};clocks[path]=clock;setPath(state,path,value);save();if(broadcast&&squad)squad.sendOp({path,value,clock})}
function remoteSet(path,value,clock){if(!newer(clock,clocks[path]))return false;lamport=Math.max(lamport,clock.n);clocks[path]=clock;setPath(state,path,value);save();return true}
function el(tag,a={},...kids){const n=document.createElement(tag);for(const[k,v]of Object.entries(a)){if(k==="class")n.className=v;else if(k.startsWith("on"))n.addEventListener(k.slice(2).toLowerCase(),v);else if(v!==false&&v!=null)n.setAttribute(k,v===true?"":v)}for(const c of kids.flat()){if(c==null)continue;n.append(c?.nodeType?c:document.createTextNode(String(c)))}return n}
function map(){return DATA.maps.find(m=>m.id===state.activeMap)}
function sections(){const m=map();if(!m?.sections)return[];return state.mode==="neko"?m.sections.filter(s=>s.neko):m.sections}
function allSteps(){return sections().flatMap(s=>s.steps.map(st=>({...st,sectionId:s.id,sectionTitle:s.title,key:`${s.id}.${st.id}`})))}
function current(){return allSteps().find(s=>!state.progress[s.key])}
function stats(){const a=allSteps(),done=a.filter(s=>state.progress[s.key]).length;return{done,total:a.length,pct:a.length?Math.round(done/a.length*100):0}}
function render(){const app=$("#app");app.innerHTML="";if(!state.activeMap){app.append(mapSelect());return}if(!map()?.available){state.activeMap=null;save();app.append(mapSelect());return}if(!state.mode){app.append(modeSelect());return}app.append(shell())}
function mapSelect(){const w=el("div",{class:"shell",style:"padding-top:max(32px,env(safe-area-inset-top));padding-bottom:32px"});w.append(el("div",{class:"hero card"},el("div",{class:"eyebrow"},"Mobile Squad Guide"),el("h1",{},"Zombies Guide"),el("p",{class:"muted"},"Wähle eine Karte. Fortschritt bleibt lokal gespeichert.")));const g=el("div",{class:"stack",style:"margin-top:14px"});DATA.maps.forEach(m=>g.append(el("button",{class:"card map-card",disabled:!m.available,onClick:()=>{localSet("activeMap",m.id);render()}},el("div",{class:"section-title"},el("div",{},el("div",{style:"font-weight:900;font-size:1.08rem"},m.name),el("div",{class:"small muted"},m.subtitle)),!m.available?el("span",{class:"pill"},"Bald"):null))));w.append(g);return w}
function modeSelect(){const w=el("div",{class:"shell",style:"padding-top:max(32px,env(safe-area-inset-top));padding-bottom:32px"});w.append(el("button",{class:"btn ghost",onClick:()=>{localSet("activeMap",null);render()}},"← Andere Map"),el("div",{class:"hero card",style:"margin-top:10px"},el("div",{class:"eyebrow"},"Kowakujō"),el("h1",{},"Modus wählen"),el("p",{class:"muted"},"Später jederzeit änderbar.")));const g=el("div",{class:"stack",style:"margin-top:14px"});map().modes.forEach(m=>g.append(el("button",{class:"btn block primary",onClick:()=>{localSet("mode",m.id);render()}},`${m.name} — ${m.description}`)));w.append(g);return w}
function shell(){const w=el("div",{class:"app"}),s=stats(),cur=current();w.append(el("header",{class:"topbar"},el("div",{class:"shell"},el("div",{class:"topbar-row"},el("div",{},el("div",{class:"brand"},"Kowakujō"),el("div",{class:"subbrand"},state.mode==="neko"?"Nur Nekomancer":"Hauptquest")),state.squadCode?el("span",{class:`squad-status ${squad?.online?"online":""}`},`${squad?.online?"●":"○"} ${state.squadCode}`):null),el("div",{class:"progress-meta"},el("span",{},`${s.done} / ${s.total} Schritte`),el("span",{class:"code"},`${s.pct}%`)),el("div",{class:"progress"},el("span",{style:`width:${s.pct}%`})))));const main=el("main",{class:"shell"},el("div",{class:"notice"},"Community-Guide: Inhalte und mögliche Bereiche können sich durch Updates ändern. Unbestätigte Spawnpunkte werden nicht als exakte Positionen dargestellt."));const view=el("div",{class:"stack",style:"margin-top:14px"});({guide:guideView,map:mapView,focus:focusView,squad:squadView,settings:settingsView}[state.tab]||guideView)(view,cur);main.append(view);w.append(main,nav());if(undoSnapshot)w.append(el("div",{class:"toast"},el("button",{class:"btn ghost",onClick:undo},"↶ Rückgängig")));return w}
function nav(){const items=[["guide","☷","Guide"],["map","⌖","Karte"],["focus","◎","Fokus"],["squad","👥","Squad"],["settings","⚙","Mehr"]],inner=el("div",{class:"bottom-nav-inner"});items.forEach(([id,ic,l])=>inner.append(el("button",{class:`nav-btn ${state.tab===id?"active":""}`,onClick:()=>{state.tab=id;save();render()}},el("span",{style:"font-size:1.2rem"},ic),l)));return el("nav",{class:"bottom-nav"},inner)}
function guideView(view,cur){if(cur)view.append(el("button",{class:"hero card",style:"text-align:left;width:100%",onClick:()=>{state.focusKey=cur.key;state.tab="focus";save();render()}},el("div",{class:"eyebrow"},"Aktueller Schritt · Fokus öffnen"),el("h2",{style:"margin:6px 0"},cur.title),el("p",{class:"muted small",style:"margin:0"},cur.description)));view.append(el("label",{class:"search"},el("span",{},"⌕"),el("input",{placeholder:"Schritte und Bereiche suchen…",value:state.query||"",onInput:e=>{state.query=e.target.value;save();render()}})),sideQuest());const q=(state.query||"").trim().toLowerCase();sections().forEach(sec=>{const visible=sec.steps.filter(st=>!q||[st.title,st.description,...(st.zones||[]).map(z=>DATA.zones[z])].join(" ").toLowerCase().includes(q));if(visible.length)view.append(sectionCard(sec,visible,cur?.key))})}
function sideQuest(){const b=el("section",{class:"card card-pad"},el("div",{class:"eyebrow"},"Nebenmission"),el("h3",{style:"margin:5px 0 10px"},state.sideQuest===null?"Welche Mission ist aktiv?":state.sideQuest==="unknown"?"Noch unbekannt":state.sideQuest));if(state.sideQuest===null||state.sideQuest==="unknown"){const g=el("div",{class:"grid3"});[["Merchant","🛒"],["Gardener","🌱"],["Noble","🍶"]].forEach(([n,i])=>g.append(el("button",{class:"btn",onClick:()=>{localSet("sideQuest",n);render()}},`${i} ${n}`)));g.append(el("button",{class:"btn ghost wide",onClick:()=>{localSet("sideQuest","unknown");render()}},"Noch unbekannt"));b.append(g)}else b.append(el("p",{class:"small muted"},"Konkrete Anleitung mit der aktiven Ingame-Variante abgleichen."),el("button",{class:"btn ghost",onClick:()=>{localSet("sideQuest",null);render()}},"Ändern"));return b}
function sectionCard(sec,steps,curKey){const done=sec.steps.filter(s=>state.progress[`${sec.id}.${s.id}`]).length,pct=Math.round(done/sec.steps.length*100),open=state.openSection===sec.id||steps.some(s=>`${sec.id}.${s.id}`===curKey)||!!state.query,body=el("div",{class:`steps ${open?"":"hidden"}`});steps.forEach(st=>body.append(stepRow(sec,st,curKey)));return el("section",{class:"section"},el("button",{class:"section-head",onClick:()=>{state.openSection=open?null:sec.id;save();render()}},el("div",{class:"section-title"},el("div",{},el("div",{style:"font-weight:900"},sec.title),el("div",{class:"small muted"},sec.subtitle||"")),el("span",{class:"code tiny"},`${done}/${sec.steps.length}`)),el("div",{class:"section-bar"},el("span",{style:`width:${pct}%`}))),body)}
function stepRow(sec,st,curKey){const key=`${sec.id}.${st.id}`,done=!!state.progress[key],fav=!!state.favorites[key],open=!!state.details?.[key],row=el("div",{class:`step ${done?"done":""}`});row.append(el("button",{class:`check ${done?"done":""}`,onClick:()=>toggle(key)},done?"✓":""),el("div",{},el("div",{class:"step-title"},st.title),el("div",{class:"step-desc"},st.description),el("button",{class:"btn ghost small",style:"padding:6px 0;min-height:auto",onClick:()=>{state.details??={};state.details[key]=!open;save();render()}},open?"Weniger":"Details")),el("button",{class:`icon-btn ${fav?"active":""}`,onClick:()=>{localSet(`favorites.${key}`,!fav);render()}},fav?"★":"☆"));if(open){const d=el("div",{class:"details"});if(st.zones?.length)d.append(el("div",{},el("div",{class:"tiny muted",style:"margin-bottom:6px"},"Mögliche Bereiche"),el("div",{class:"zone-pills"},...st.zones.map(z=>el("span",{class:"pill"},DATA.zones[z]||z)))));if(st.roles)d.append(el("div",{class:"small muted"},`Empfohlene Squad-Beteiligung: ${Math.min(st.roles,state.players)} Spieler`));if(st.note)d.append(el("label",{class:"tiny muted"},st.note),el("textarea",{class:"note",placeholder:st.note,value:state.notes[key]||"",onInput:e=>localSet(`notes.${key}`,e.target.value)}));row.append(d)}if(key===curKey)row.style.background="rgba(249,115,22,.045)";return row}
function toggle(key){const before=!!state.progress[key];undoSnapshot={key,value:before};clearTimeout(undoTimer);undoTimer=setTimeout(()=>{undoSnapshot=null;render()},5000);localSet(`progress.${key}`,!before);render()}
function undo(){if(!undoSnapshot)return;localSet(`progress.${undoSnapshot.key}`,undoSnapshot.value);undoSnapshot=null;clearTimeout(undoTimer);render()}
function focusView(view){const all=allSteps(),cur=current();if(!all.length){view.append(el("div",{class:"card complete"},"Keine Schritte vorhanden."));return}if(!cur&&!state.focusKey){view.append(completeView());return}let idx=all.findIndex(s=>s.key===(state.focusKey||cur?.key));if(idx<0)idx=0;const st=all[idx],done=!!state.progress[st.key];view.append(el("div",{class:"focus-actions"},el("button",{class:"btn",disabled:idx===0,onClick:()=>{state.focusKey=all[idx-1].key;save();render()}},"← Vorher"),el("span",{class:"code tiny"},`${idx+1}/${all.length}`),el("button",{class:"btn",disabled:idx===all.length-1,onClick:()=>{state.focusKey=all[idx+1].key;save();render()}},"Weiter →")));view.append(el("section",{class:"hero card focus-card"},el("div",{class:"eyebrow"},st.sectionTitle),el("h2",{class:"focus-title",style:"margin:7px 0 12px"},st.title),el("p",{class:"muted",style:"line-height:1.55"},st.description)));if(st.zones?.length)view.append(el("section",{class:"card card-pad"},el("div",{class:"tiny muted",style:"margin-bottom:8px"},"Mögliche Bereiche"),el("div",{class:"zone-pills"},...st.zones.map(z=>el("span",{class:"pill"},DATA.zones[z]||z)))));if(st.note)view.append(el("section",{class:"card card-pad"},el("label",{class:"tiny muted"},st.note),el("textarea",{class:"note",value:state.notes[st.key]||"",onInput:e=>localSet(`notes.${st.key}`,e.target.value)})));view.append(el("button",{class:`btn block ${done?"":"primary"}`,onClick:()=>{toggle(st.key);state.focusKey=all[idx+1]?.key||null;save();render()}},done?"↺ Wieder öffnen":"✓ Erledigt → weiter"));if(!cur)view.append(completeView())}
function completeView(){return el("section",{class:"card complete"},el("div",{style:"font-size:2.4rem"},"✓"),el("h2",{},"Checkliste abgeschlossen"),el("p",{class:"muted"},"Alle Schritte dieses Modus sind abgehakt."),el("button",{class:"btn",onClick:()=>{state.tab="guide";save();render()}},"Zur Übersicht"))}
const zoneLayout=[["outerward",20,24,460,54],["gatehouse",200,88,100,46],["stables",28,88,140,58],["training",332,88,140,58],["courtyard",130,158,240,82],["teagarden",28,170,90,64],["garden",382,170,90,64],["kitchens",28,252,110,56],["storage",148,252,90,56],["warroom",248,252,100,56],["study",358,252,114,56],["workshop",28,320,110,56],["meditation",148,320,130,56],["staging",288,320,90,56],["onsen",388,320,84,56],["tenshu",170,396,160,52],["sanctum",180,464,140,52]];
function mapView(view){const cur=current(),highlight=new Set(cur?.zones||[]),svg=el("svg",{class:"svg-map",viewBox:"0 0 500 540",role:"img","aria-label":"Schematische Karte"});zoneLayout.forEach(([id,x,y,w,h])=>{const g=el("g",{tabindex:"0",role:"button","aria-label":DATA.zones[id],onClick:()=>{state.activeZone=id;save();render()},onKeydown:e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();state.activeZone=id;save();render()}}});g.append(el("rect",{class:`zone-shape ${highlight.has(id)?"highlight":""} ${state.activeZone===id?"active":""}`,x,y,width:w,height:h,rx:"9"}),el("text",{class:"zone-label",x:x+w/2,y:y+h/2+4},DATA.zones[id]));svg.append(g)});view.append(svg,el("div",{class:"notice"},"Schematische Orientierung, kein exaktes Ingame-Layout."));if(state.activeZone){const matches=allSteps().filter(s=>s.zones?.includes(state.activeZone)),inner=el("div",{class:"zone-list"}),sec=el("section",{class:"card card-pad"},el("div",{class:"eyebrow"},DATA.zones[state.activeZone]),inner);if(!matches.length)inner.append(el("p",{class:"muted small"},"Keine zugeordneten Schritte."));matches.forEach(s=>inner.append(el("button",{class:"btn block",style:"text-align:left",onClick:()=>{state.focusKey=s.key;state.tab="focus";save();render()}},`${state.progress[s.key]?"✓ ":""}${s.title}`)));view.append(sec)}}
function squadView(view){const configured=!!(CFG.supabaseUrl&&CFG.supabaseAnonKey),panel=el("section",{class:"card card-pad"},el("div",{class:"eyebrow"},"Online Squad"),el("p",{class:"small muted"},configured?"Raumcode teilen. Änderungen werden zwischen verbundenen Geräten synchronisiert.":"Ohne Supabase-Konfiguration bleibt die App lokal. URL und Publishable/Anon Key können später in config.js eingetragen werden."));if(!configured){panel.append(el("pre",{class:"notice code",style:"white-space:pre-wrap"},'window.KOWA_CONFIG = {\n  supabaseUrl: "…",\n  supabaseAnonKey: "…"\n};'));view.append(panel,assignments());return}if(!state.squadCode){const name=el("input",{class:"note",style:"min-height:46px",placeholder:"Dein Name",value:state.playerName||"",onInput:e=>{state.playerName=e.target.value;save()}}),code=el("input",{class:"note code",style:"min-height:46px;margin-top:10px",placeholder:"RAUMCODE",maxlength:"8"});panel.append(name,code,el("div",{class:"grid2",style:"margin-top:10px"},el("button",{class:"btn primary",onClick:()=>connectSquad(randomCode(),true)},"Squad erstellen"),el("button",{class:"btn",onClick:()=>connectSquad(code.value,false)},"Beitreten")))}else{panel.append(el("div",{class:"section-title"},el("div",{class:"code",style:"font-size:1.4rem"},state.squadCode),el("span",{class:`squad-status ${squad?.online?"online":""}`},squad?.online?"Online":"Verbinden…")),el("div",{class:"grid2",style:"margin-top:10px"},el("button",{class:"btn",onClick:shareRoom},"Link teilen"),el("button",{class:"btn danger",onClick:leaveSquad},"Session verlassen")));if(squad?.members?.length)panel.append(el("div",{class:"small muted",style:"margin-top:10px"},`Teilnehmer: ${squad.members.map(m=>m.name).join(", ")}`))}view.append(panel,assignments())}
function assignments(){const open=allSteps().filter(s=>!state.progress[s.key]&&s.roles),names=Array.from({length:state.players},(_,i)=>`Spieler ${i+1}`),groups=Object.fromEntries(names.map(n=>[n,[]]));open.forEach((s,i)=>{for(let j=0;j<Math.min(s.roles,state.players);j++)groups[names[(i+j)%names.length]].push(s.title)});const controls=el("div",{class:"grid3"});[2,3,4].forEach(n=>controls.append(el("button",{class:"btn",onClick:()=>{localSet("players",n);render()}},n)));const sec=el("section",{class:"card card-pad"},el("div",{class:"section-title"},el("div",{},el("div",{class:"eyebrow"},"Squad-Aufteilung"),el("div",{class:"small muted"},`${state.players} Spieler`)),controls)),grid=el("div",{class:"grid2",style:"margin-top:12px"});Object.entries(groups).forEach(([n,t])=>grid.append(el("div",{class:"notice"},el("strong",{},n),el("div",{class:"tiny",style:"margin-top:6px"},t.slice(0,5).join(" · ")||"Keine offenen Rollen-Aufgaben"))));sec.append(grid);return sec}
function randomCode(){const a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:5},()=>a[Math.floor(Math.random()*a.length)]).join("")}
async function connectSquad(code,create){code=String(code||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,8);if(!code)return alert("Bitte Raumcode eingeben.");state.squadCode=code;save();await initSquad(code);render();if(create)squad?.sendSnapshot()}
function leaveSquad(){squad?.close();squad=null;state.squadCode=null;save();render()}
async function shareRoom(){const u=new URL(location.href);u.searchParams.set("squad",state.squadCode);if(navigator.share)await navigator.share({title:"Kowakujō Squad",url:u.href}).catch(()=>{});else{await navigator.clipboard.writeText(u.href);alert("Link kopiert.")}}
function settingsView(view){view.append(el("section",{class:"card card-pad"},el("div",{class:"eyebrow"},"Navigation"),el("div",{class:"grid2",style:"margin-top:10px"},el("button",{class:"btn",onClick:()=>{localSet("activeMap",null);localSet("mode",null);localSet("goal",null);render()}},"Andere Map"),el("button",{class:"btn",onClick:()=>{localSet("mode",null);localSet("goal",null);render()}},"Modus wechseln"),el("button",{class:"btn",onClick:()=>{localSet("goal",null);render()}},"Run-Ziel wechseln"))));const out=()=>({version:2,activeMap:state.activeMap,mode:state.mode,goal:state.goal,bossPrep:state.bossPrep,progress:state.progress,notes:state.notes,favorites:state.favorites,players:state.players,sideQuest:state.sideQuest}),ta=el("textarea",{class:"note",placeholder:"Export-Code hier einfügen…"});view.append(el("section",{class:"card card-pad"},el("div",{class:"eyebrow"},"Sichern & übertragen"),el("div",{class:"grid2",style:"margin-top:10px"},el("button",{class:"btn",onClick:async()=>{await navigator.clipboard.writeText(JSON.stringify(out()));alert("Export kopiert.")}},"Export kopieren"),el("button",{class:"btn",onClick:()=>download("kowakujo-progress.json",JSON.stringify(out(),null,2))},"JSON-Datei")),ta,el("button",{class:"btn block",style:"margin-top:10px",onClick:()=>{try{const x=JSON.parse(ta.value);["activeMap","mode","goal","bossPrep","progress","notes","favorites","players","sideQuest"].forEach(k=>{if(k in x)state[k]=x[k]});save();render()}catch{alert("Ungültiger Export.")}}},"Importieren")));view.append(el("section",{class:"card card-pad"},el("div",{class:"eyebrow"},"iPhone"),el("p",{class:"small muted"},"In Safari: Teilen → Zum Home-Bildschirm. Die lokale Checkliste ist danach auch offline verfügbar.")),el("section",{class:"card card-pad"},el("button",{class:"btn danger block",onClick:()=>{if(confirm("Gesamten lokalen Fortschritt löschen?")){squad?.close();squad=null;state=structuredClone(defaults);clocks={};save();render()}}},"Lokalen Fortschritt löschen")))}
function download(name,text){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"application/json"}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
class Squad{constructor(client,code){this.client=client;this.code=code;this.channel=null;this.online=false;this.members=[]}async open(){this.channel=this.client.channel(`kowa-${this.code}`,{config:{presence:{key:actorId},broadcast:{self:false}}});this.channel.on("presence",{event:"sync"},()=>{const p=this.channel.presenceState();this.members=Object.entries(p).map(([id,v])=>({id,name:v[0]?.name||`Spieler ${id.slice(-3)}`}));render()});this.channel.on("broadcast",{event:"op"},({payload})=>{if(remoteSet(payload.path,payload.value,payload.clock))render()});this.channel.on("broadcast",{event:"snapshot-request"},()=>this.sendSnapshot());this.channel.on("broadcast",{event:"snapshot"},({payload})=>{let changed=false;Object.entries(payload.clocks||{}).forEach(([path,clock])=>{if(remoteSet(path,getPath(payload.state,path),clock))changed=true});if(changed)render()});await new Promise((resolve,reject)=>this.channel.subscribe(async s=>{if(s==="SUBSCRIBED"){this.online=true;await this.channel.track({name:state.playerName||`Spieler ${actorId.slice(-3)}`});await this.channel.send({type:"broadcast",event:"snapshot-request",payload:{}});resolve()}if(s==="CHANNEL_ERROR"||s==="TIMED_OUT")reject(new Error(s))}))}sendOp(op){if(this.online)this.channel.send({type:"broadcast",event:"op",payload:op})}sendSnapshot(){if(this.online)this.channel.send({type:"broadcast",event:"snapshot",payload:{state,clocks}})}close(){this.channel?.unsubscribe()}}
async function initSquad(code){if(!(CFG.supabaseUrl&&CFG.supabaseAnonKey))return;try{const{createClient}=await import("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm"),client=createClient(CFG.supabaseUrl,CFG.supabaseAnonKey,{auth:{persistSession:false,autoRefreshToken:false}});squad?.close();squad=new Squad(client,code);await squad.open()}catch(e){console.error(e);alert("Squad-Verbindung fehlgeschlagen. Lokale Nutzung bleibt aktiv.")}}
async function boot(){const urlCode=new URLSearchParams(location.search).get("squad");if(urlCode&&CFG.supabaseUrl&&CFG.supabaseAnonKey){state.squadCode=urlCode.toUpperCase();save();initSquad(state.squadCode).then(render)}else if(state.squadCode&&CFG.supabaseUrl&&CFG.supabaseAnonKey)initSquad(state.squadCode).then(render);render();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(console.warn)}
boot();
})();
